### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by bebatut** [marbl/VALET#7]
Hi,

I would like to create a [Bioconda](http://bioconda.github.io/) recipe for your tool. It would be easier if there is a release of the tool. Is it possible for you to create one?

Thanks a lot,

Bérénice

**Comment by nate-d-olson** [comment]
Thanks for creating a Bioconda recipe for VALET. We created a v1.0 tagged release to help you with creating the recipe. I am closing this issue for now. Please re-open if you run into any problems creating the bioconda recipe.
